# parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple



# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# yolov7-tiny backbone
backbone:
  # [from, number, module, args] c2, k=1, s=1, p=None, g=1, act=True
  [[-1, 1, Conv, [32, 3, 2, None, 1, nn.PReLU()]],  # 0-P1/2  
  
   [-1, 1, Conv, [64, 3, 2, None, 1, nn.PReLU()]],  # 1-P2/4    
   
   [-1, 1, C3, [64]], 
   [-1, 1, Conv, [128, 3, 2]],
   [-1, 1, MP, []],

   [-1, 1, Conv, [32, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [32, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [32, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [32, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],  # 10
   
   [-1, 1, MP, []],  # 11-P3/8
   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],  # 17
   
   [-1, 1, MP, []],  # 18-P4/16
   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],  # 24
   
   [-1, 1, MP, []],  # 25-P5/32
   [-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [256, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [256, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, C3, [512]],
   [-1, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],  # 32
  ]

# yolov7-tiny head
head:
  [[-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, SP, [5]],
   [-2, 1, SP, [9]],
   [-3, 1, SP, [13]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],
   [[-1, -7], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],  # 41
  
   [-1, 1, C3, [128]], ### 42

   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [24, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],
   
   [-1, 1, C3, [128]],
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, eca_layer, [128]],

   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],  # 56
  
   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [17, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]], # route backbone P3
   [[-1, -2], 1, Concat, [1]],
   
   [-1, 1, Conv, [32, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [32, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [32, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [32, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],  # 66
   
   [-1, 1, Conv, [128, 3, 2, None, 1, nn.PReLU()]],
   [[-1, 56], 1, Concat, [1]],
   
   [-1, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [64, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [64, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],  # 74

   [-1, 1, C3, [128]],
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, CBAM, [128]],
   
   [-1, 1, Conv, [256, 3, 2, None, 1, nn.PReLU()]],
   [[-1, 41], 1, Concat, [1]],
   
   [-1, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],
   [-2, 1, Conv, [128, 1, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],
   [-1, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],
   [[-1, -2, -3, -4], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1, None, 1, nn.PReLU()]],  # 86
      
   [66, 1, Conv, [128, 3, 1, None, 1, nn.PReLU()]],
   [74, 1, Conv, [256, 3, 1, None, 1, nn.PReLU()]],
   [86, 1, Conv, [512, 3, 1, None, 1, nn.PReLU()]],

   [[87,88,89], 1, IDetect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
